### ISSUE TITLE
Support for weights loading in lower precision

### ISSUE THREAD

**Issue by alzaia** [linzhiqiu/t2v_metrics#8]
Hello again, I was also wondering if there is a way to set the weights precision (e.g. 4bit quantization support) when doing inference to avoid getting out of memory? I am having trouble loading the `clip-flant5-xxl` model in a A100 without going OOM.

**Comment by linzhiqiu** [comment]
Hey, I never tested CLIP-FlanT5 models using 4-bit quantization. The default quantization follows FlanT5's bfloat16:

https://github.com/linzhiqiu/t2v_metrics/blob/2df936838bfb8ec8e4e071c58e93c23e81fed2c8/t2v_metrics/models/vqascore_models/clip_t5_model.py#L219

You may consider modifying this line (make sure to ``pip install -e .'' again); however, I don't know if this will cause weird model behaviors (e.g., FlanT5 produces bad performance when using float16 instead of bfloat16).

On the other hand, A100 (with 40GB+ RAM?) should be able to load clip-flant5-xxl.
